backend:
  name: github
  repo: hrajput328/Cherry-furniture
  branch: main
  base_url: https://sveltia-cms-auth.pages.dev

media_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files: []
