backend:
  name: git-gateway
  branch: main # or master, depending on your default branch name

local_backend: true # Add this exact line here

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
